"use client"

import React, { ReactNode } from 'react'
import { ThemeProvider } from '@mui/material/styles'
import { muiTheme } from '@/lib/mui-theme'
import {
  TextField,
  Button,
  ButtonGroup,
  Checkbox,
  Fab,
  FormControl,
  FormControlLabel,
  FormLabel,
  Radio,
  RadioGroup,
  Rating,
  Select,
  MenuItem,
  Slider,
  Switch,
  ToggleButton,
  ToggleButtonGroup,
  Autocomplete,
  Avatar,
  Badge,
  Chip,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemAvatar,
  ListItemButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Tooltip,
  Typography,
  Alert,
  Backdrop,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  LinearProgress,
  CircularProgress,
  Skeleton,
  Snackbar,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  AppBar,
  Toolbar,
  Card,
  CardContent,
  CardActions,
  CardMedia,
  BottomNavigation,
  BottomNavigationAction,
  Breadcrumbs,
  Drawer,
  Link,
  Menu,
  Pagination,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  Stepper,
  Step,
  StepLabel,
  StepContent,
  Tabs,
  Tab,
  Box,
  Grid,
  IconButton,
  FormGroup,
  InputAdornment,
  OutlinedInput,
  FilledInput,
  Input,
  FormHelperText,
  ListItemIcon,
  ListItemSecondaryAction,
  ListSubheader,
  TablePagination,
  TableSortLabel,
  CardActionArea,
  Popper,
  Grow,
  Fade,
  Zoom,
  Slide,
  Collapse,
  StepConnector,
  StepIcon,
  MobileStepper,
  Popover
} from '@/components'

interface MuiThemeProviderProps {
  children: ReactNode;
}

export function MuiThemeProvider({ children }: MuiThemeProviderProps) {
  return (
    <ThemeProvider theme={muiTheme}>
      {children}
    </ThemeProvider>
  );
} 